import MoviesContextProvider from "@/context/MoviesContextProvider";
import "@styles/globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";

const geistSans = localFont({
  src: "../assets/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../assets/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Cinemate",
  description: "Generated by create next app",
};
type RootLayoutType = Readonly<{ children: React.ReactNode; }>

export default function RootLayout({ children, }: RootLayoutType) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MoviesContextProvider>
          {children}
        </MoviesContextProvider>
      </body>
    </html>
  );
}
